06_pjt/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns =[
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('update/', views.update, name='update'),
    path('delete/', views.delete, name='delete'),
    path('change_password/', views.change_password, name='change_password'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('<int:pk>/follow/', views.follow, name='follow'),
]

06_pjt/movies/urls.py
from django.urls import path
from . import views


app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/likes/', views.likes, name='likes'),
    path('<int:movie_pk>/comments_create/', views.comments_create, name='comments_create'),
    path('<int:movie_pk>/comments_delete/<int:comment_pk>', views.comments_delete, name='comments_delete'),
]

06_pjt/mypjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
]

06_pjt/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    followings = models.ManyToManyField('self', symmetrical=False, related_name='followers')
    pass

06_pjt/movies/models.py
from django.db import models
from django.conf import settings

class Movie(models.Model):
    user_id = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_movies')
    title = models.CharField(max_length=20)
    description = models.TextField()

    def __str__(self):
        return self.title

class Comment(models.Model):
    user_id = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.CharField(max_length=100)
    movie_id = models.ForeignKey(Movie, on_delete=models.CASCADE)

06_pjt/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()

class CustomUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = ('first_name', 'last_name',)

06_pjt/accounts/views.py
from django.shortcuts import render, redirect
from .forms import CustomUserCreationForm, CustomUserChangeForm
from django.contrib.auth import get_user_model, update_session_auth_hash
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import login as auth_login, logout as auth_logout

# Create your views here.


def login(request):
    if request.method == "POST":
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('movies:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/login.html', context)

def logout(request):
    auth_logout(request)
    return redirect('movies:index')

def signup(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('movies:index')
    else:
        form = CustomUserCreationForm()
    context = {'form': form}
    return render(request, 'accounts/signup.html', context)
    


def update(request):
    if request.method == "POST":
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
        return redirect('movies:index')
    else:
        form = CustomUserChangeForm()
    context = { 'form': form }
    return render(request, 'accounts/update.html', context)

def delete(request):
    request.user.delete()
    auth_logout(request)
    return redirect('movies:index')

def change_password(request):
    user = request.user
    if request.method == "POST":
        form = PasswordChangeForm(user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('movies:index')
    else:
        form = PasswordChangeForm(user)
    context = {'form': form }
    return render(request, 'accounts/change_password.html', context)

def profile(request, username):
    User = get_user_model()
    person = User.objects.get(username = username)
    context ={'person':person}
    return render(request, 'accounts/profile.html', context)

def follow(request, pk):
    if not request.user.is_authenticated:
        return redirect('accounts:login')
    User = get_user_model()
    person = User.objects.get(pk=pk)
    if request.user == person:
        return redirect('accounts:profile', person.username)
    if person.followings.filter(pk=request.user.pk).exists():
        person.followings.remove(request.user)
    else:
        person.followings.add(request.user)
    return redirect('accounts:profile', person.username)

06_pjt/accounts/templates/accounts/change_password.html
{% extends 'base.html' %}
{% block content %}

<form action="{% url 'accounts:change_password' %}" method="POST">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit" value="제출">
</form>

{% endblock content %}

06_pjt/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}

<form action="{% url 'accounts:login' %}" method = "POST">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit" value='로그인'>
</form>

{% endblock content %}

06_pjt/accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block content %}
  <h1>{{person.username}} 님의 프로필</h1>
  <hr>
  <div>
    팔로잉 : {{person.followings.count}} | 팔로워 : {{person.followers.count}}
  </div>
  <hr>
  <form action="{% url 'accounts:follow' person.pk %}">
    {% csrf_token %}
    {% if request.user in person.followers.all %}
    <input type="submit" value="언팔로우">    
    {% else %}
    <input type="submit" value="팔로우">
    {% endif %}
  </form>
  <hr>
  <h2>{{person.username}}님이 작성한 글</h2>
  <ul>
    {% for movie in person.movie_set.all  %}
    <li><a href="{% url 'movies:detail' movie.pk %}">{{movie.title}}</a></li>
    {% endfor %}
  </ul>
  <hr>

  {% if person.like_movies.all %}
  <h2>{{person.username}}님이 좋아한 영화</h2>
  <ul>
    {% for movie in person.like_movies.all  %}
    <li><a href="{% url 'movies:detail' movie.pk %}">{{movie.title}}</a></li>
    {% endfor %}
  </ul>
  <hr>
  {% else %}
  <h2>{{person.username}}님은 아직 좋아하는 영화가 없습니다.</h2>
  {% endif %}
  <a href="{% url 'movies:index' %}">BACK</a>
  
{% endblock content %}

06_pjt/accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
  <form action="{% url 'accounts:signup' %}" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="회원가입">
  </form>
{% endblock content %}

06_pjt/accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% block content %}

<form action="{% url 'accounts:update' %}" method="POST">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit" value="회원정보수정">
</form>
<a href="{% url 'movies:index' %}">BACK</a>
{% endblock content %}