06_pjt/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns =[
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('update/', views.update, name='update'),
    path('delete/', views.delete, name='delete'),
    path('change_password/', views.change_password, name='change_password'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('<int:pk>/follow/', views.follow, name='follow'),
]

06_pjt/movies/urls.py
from django.urls import path
from . import views


app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/likes/', views.likes, name='likes'),
    path('<int:movie_pk>/comments_create/', views.comments_create, name='comments_create'),
    path('<int:movie_pk>/comments_delete/<int:comment_pk>', views.comments_delete, name='comments_delete'),
]

06_pjt/mypjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
]

06_pjt/movies/models.py
from django.db import models
from django.conf import settings

class Movie(models.Model):
    user_id = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_movies')
    title = models.CharField(max_length=20)
    description = models.TextField()

    def __str__(self):
        return self.title

class Comment(models.Model):
    user_id = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.CharField(max_length=100)
    movie_id = models.ForeignKey(Movie, on_delete=models.CASCADE)

06_pjt/movies/forms.py
from django import forms
from .models import Movie, Comment


class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ('title', 'description')

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)
        

06_pjt/movies/views.py
from django.shortcuts import render, redirect
from .models import Movie, Comment
from .forms import MovieForm, CommentForm
from django.views.decorators.http import require_POST, require_safe


def index(request):
    movies = Movie.objects.all()
    context = {
        'movies': movies,
    }
    return render(request, 'movies/index.html', context)


def create(request):
    if not request.user.is_authenticated:
        return redirect('accounts:login')
    if request.method == 'POST':
        form = MovieForm(request.POST)
        if form.is_valid():
            movie = form.save(commit=False)
            movie.user_id = request.user
            movie.save()
            return redirect('movies:detail', movie.pk)
    else:
        form = MovieForm()
    context = {
        'form': form,
    }
    return render(request, 'movies/create.html', context)


def detail(request, pk):
    movie = Movie.objects.get(pk=pk)
    comment_form = CommentForm()
    comments = movie.comment_set.all()
    context = {
        'comment_form' : comment_form,
        'movie': movie,
        'comments': comments,
    }
    return render(request, 'movies/detail.html', context)


def delete(request, pk):
    if not request.user.is_authenticated:
        return redirect('accounts:login')
    
    movie = Movie.objects.get(pk=pk)
    if request.user == movie.user_id:
        movie.delete()
        return redirect('movies:index')
    return redirect('movies:detial', pk)


def update(request, pk):
    if not request.user.is_authenticated:
        return redirect('accounts:login')

    movie = Movie.objects.get(pk=pk)
    if request.method == 'POST':
        form = MovieForm(request.POST, instance=movie)
        if form.is_valid():
            form.save()
            return redirect('movies:detail', movie.pk)
    else:
        form = MovieForm(instance=movie)
    context = {
        'movie': movie,
        'form': form,
    }
    return render(request, 'movies/update.html', context)

def comments_create(request, movie_pk):
    if not request.user.is_authenticated:
        return redirect('accounts:login')
    comment_form = CommentForm(request.POST)    
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.movie_id = Movie.objects.get(pk=movie_pk)
        comment.user_id = request.user
        comment.save()
        return redirect('movies:detail', pk=movie_pk)
    
@require_POST
def comments_delete(request, movie_pk, comment_pk):
    if not request.user.is_authenticated:
        return redirect('accounts:login')
    comments =Comment.objects.get(pk=comment_pk)
    comments.delete()
    return redirect('movies:detail', pk = movie_pk)

@require_POST
def likes(request, pk):
    if request.user.is_authenticated:
        movie = Movie.objects.get(pk=pk)
        if movie.like_users.filter(pk=request.user.pk).exists():
            movie.like_users.remove(request.user)
        else:
            movie.like_users.add(request.user)
        return redirect('movies:index')
    return redirect('accounts:login')

06_pjt/movies/templates/movies/create.html
{% extends 'base.html' %}

{% block content %}
  <h1>CREATE</h1>
  <hr>
  <form action="{% url 'movies:create' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
  </form>
  <hr>
  <a href="{% url 'movies:index' %}">BACK</a>
{% endblock %}

06_pjt/movies/templates/movies/detail.html
{% extends 'base.html' %}

{% block content %}
  <h1>DETAIL</h1>
  <hr>
  <div>
    <h5>{{ movie.title }}</h5>
    <p>{{ movie.description }}</p>
  </div>
  {% if request.user == movie.user_id %}
  <a href="{% url 'movies:update' movie.pk %}">UPDATE</a>
  <form action="{% url 'movies:delete' movie.pk %}" method="POST">
    {% csrf_token %}
    <input type="submit" value="DELETE">
  </form>
  {% endif %}
  <a href="{% url 'movies:index' %}">BACK</a> 
  <hr>
  {% for comment in comments %}
    <ul>
      <li>{{comment.user_id}}: {{comment.content}}</li>
      {% if request.user == comment.user_id %}
      <form action="{% url 'movies:comments_delete' movie.pk comment.pk %}" method = "POST">
        {% csrf_token %}
        <input type="submit" value="삭제">
      </form>
      {% endif %}
    </ul>
  {% endfor %}

  <hr>
  <form action="{% url 'movies:comments_create' movie.pk %}" method="POST">
    {% csrf_token %}
    {{comment_form.as_p}}
    <input type="submit" value="작성">
  </form>


  <hr>
{% endblock  %}

06_pjt/movies/templates/movies/index.html
{% extends 'base.html' %}

{% block content %}
  <h1>INDEX</h1>
  <a href="{% url 'movies:create' %}">[CREATE]</a>
  <hr>
  {% for movie in movies %}
    <a href="{% url 'movies:detail' movie.pk %}"><p>{{ movie.title }}</p></a>
    <form action="{% url 'movies:likes' movie.pk %}" method="POST">
      {% csrf_token %}
      {% if request.user in movie.like_users.all %}
        <input type="submit" value="좋아요 취소">
      {% else %}
        <input type="submit" value="좋아요">
      
      {% endif %}
    </form>
    <p>작성자 : <a href="{% url 'accounts:profile' movie.user_id.username %}">{{movie.user_id}}</a></p>
    <hr>
  {% endfor %}
{% endblock %}

06_pjt/movies/templates/movies/update.html
{% extends 'base.html' %}

{% block content %}
  <h1>UPDATE</h1>
  <hr>
  <form action="{% url 'movies:update' movie.pk %}" method="POST">
    {% csrf_token %}
    <div>
      <label for="title">TITLE</label>
      <input type="text" id="title" name="title" value="{{ movie.title }}">
    </div>
    <div>
      <label for="description">DESCRIPTION</label>
      <textarea id="description" rows="3" name="description">{{ movie.description }}</textarea>
    </div>
    <input type="reset" value="Reset">
    <button type="submit">Submit</button>
  </form>
  <hr>
  <a href="{% url 'movies:detail' movie.pk %}">BACK</a>
{% endblock %}